export enum States {
    PENDING_FOR_VARIABLE,
    READY_FOR_CONSUMING,
    CONSUMING_VARIABLE,
    CANCEL_NEXT_TOKEN,
    CANCEL_PREV_TOKEN,
    TOKEN_PERSISTED,
    STRING_CONSUMING,
    STRING_CONSUMED,
    EXPECT_ASSIGNING,
    VARIABLE_DECLARATION_SET
}